services:
  postgres:
    image: 'postgres:16'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5999:5432"

volumes:
  postgres_data: